Repository anand-harsh/Edumi, pull requests merged in 2024-01, with the labels that each got.

#61 Added an admin functionality to delete any user
  controllers/userController.js
  routes/userRoutes.js
Labels: JWOC, medium

#62 Added a Admin functionality to get all user
  controllers/userController.js
  routes/userRoutes.js
Labels: JWOC, medium

#66 Enhanced GoToTopButton
  client/src/components/Button/GoToTopButton.jsx
Labels: JWOC, easy

#63 Adding Route for User Role Updation
  controllers/userController.js
  routes/userRoutes.js
Labels: JWOC, hard

#70 ADD:LinkedIn,Insta and portfolio of Admin
  client/src/components/Layout/Footer/Footer.jsx
Labels: JWOC, easy

#68 Added lecture to specific playlist
  controllers/courseController.js
  middlewares/catchAsyncError.js
  models/Course.js
  routes/courseRoutes.js
Labels: JWOC, hard

#69 Create Landing page.md
  Landing page.md
Labels: JWOC, hard

#75 Feature done: Updated to modern scroll bar
  client/src/style.css
Labels: JWOC, easy

#84 Adding the Lecture id when the new Lectures is inserted in the course
  controllers/courseController.js
Labels: JWOC, medium

#82 Adding Feature of Authentication
  app.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Admin/Dashboard/Menu.jsx
  client/src/components/Auth/Login.jsx
  client/src/components/Auth/ProtectedRoute.jsx
  client/src/components/Auth/Register.jsx
  client/src/components/Courses/Courses.jsx
  client/src/components/Layout/Header/Header.jsx
  client/src/components/Profile/Profile.jsx
  client/src/config/constant.js
  client/src/index.js
  controllers/userController.js
  models/User.js
  package-lock.json
  package.json
Labels: JWOC, hard

#92 ADD:Notes added
  client/.DS_Store
  client/src/.DS_Store
  client/src/App.js
  client/src/components/.DS_Store
  client/src/components/Layout/Header/Header.jsx
  client/src/components/Notes/Note.css
  client/src/components/Notes/Note.jsx
  client/src/components/Notes/NotesTab.jsx
Labels: JWOC, hard

#90 Added feature to add course to user playlist
  controllers/userController.js
  routes/courseRoutes.js
Labels: JWOC, hard

#85 Added new footer
  client/src/components/Layout/Footer/Footer.jsx
  client/src/components/Layout/Footer/footer.css
Labels: JWOC, medium
